package basm

STANDARD_INSTRUCTION_STRINGS_MAP: map[string]int
PSEUDO_INSTRUCTIONS_STRING_MAP: map[string]int

setup_instructions_maps :: proc() {
    STANDARD_INSTRUCTION_STRINGS_MAP = make(map[string]int)
    PSEUDO_INSTRUCTIONS_STRING_MAP = make(map[string]int)

    // Standard instructions
    STANDARD_INSTRUCTION_STRINGS_MAP["NOP"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["MOV"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["MVI"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["LXI"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["LDA"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["STA"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["LHLD"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["SHLD"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["LDAX"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["STAX"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["XCHG"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["ADD"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["ADI"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["ADC"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["ACI"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["SUB"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["SUI"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["SBB"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["SBI"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["INR"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["DCR"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["INX"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["DCX"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["DAD"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["DAA"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["ANA"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["ANI"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["ORA"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["ORI"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["XRA"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["XRI"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["CMP"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["CPI"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["RLC"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["RRC"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["RAL"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["RAR"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["CMA"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["CMC"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["STC"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["JMP"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["JNZ"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["JZ"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["JNC"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["JC"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["JPO"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["JPE"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["JM"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["CALL"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["CNZ"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["CZ"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["CNC"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["CC"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["CPO"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["CPE"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["CP"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["CM"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["RET"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["RNZ"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["RZ"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["RNC"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["RC"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["RPO"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["RPE"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["RP"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["RM"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["RST"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["PCHL"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["PUSH"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["POP"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["XTHL"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["SPHL"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["IN"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["OUT"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["EI"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["DI"] = 0
    STANDARD_INSTRUCTION_STRINGS_MAP["HLT"] = 0

    // Pseudo Instructions
    PSEUDO_INSTRUCTIONS_STRING_MAP["ORG"] = 0
}

